### ISSUE TITLE
老哥对这个行为怎么看？ 

### ISSUE THREAD

**Issue by sjclijie** [vimac/smile-framework#3]
<img width="788" alt="屏幕快照 2019-04-01 下午5 49 51" src="https://user-images.githubusercontent.com/3355515/55319099-c51fa300-54a6-11e9-89b4-08dec7aecff8.png">

<img width="788" alt="屏幕快照 2019-04-01 下午5 49 51" src="https://user-images.githubusercontent.com/3355515/55319283-1a5bb480-54a7-11e9-869e-20de4e6bfa87.png">

star居然比你的还多

**Comment by love10ve** [comment]
这特么真是个人渣啊

**Comment by vimac** [comment]
感谢各位还有在关注这个默默无闻的框架以及我的课程。

Panda 兄我也认识，他的做法没有什么太大的问题。

最上面截图1所示的代码也并非我编写，是来自 SlimFramework 对于 PSR-7 的标准的实现（我在教程里面提及了这个情况，也已经在 README.md 里面提到了部分代码来自于 SlimFramework ）

我的框架是 MIT 协议，而 MIT 协议的被许可人有以下权利和义务：

**被许可人权利**
被许可人有权利使用、复制、修改、合并、出版发行、散布、再许可和/或贩售软件及软件的副本，及授予被供应人同等权利，惟服从以下义务。

**被许可人义务**
在软件和软件的所有副本中都必须包含以上著作权声明和本许可声明。

（来自 Wikipedia 的中文翻译：https://zh.wikipedia.org/wiki/MIT%E8%A8%B1%E5%8F%AF%E8%AD%89 ）

他本人也已经和我联系并说明了这个情况，大家可以淡定点，宽容点哈

**Comment by qxhy123** [comment]
慕名而来，火钳刘明

**Comment by sjclijie** [comment]
散了吧，MIT协议，作者说没问题那就行了

**Comment by wujunze** [comment]
沙雕喷子  看清楚再喷 @sjclijie 

你TMD的瞎子啊？  @love10ve

**Comment by sjclijie** [comment]
@wujunze   你特么怎么这么无脸无皮啊？    让我在github上解释，又来骂我？    star是你爹？

**Comment by vimac** [comment]
大家不用戾气这么重哈，理性！
网上逞个一时口快，砖还照样得搬不是 😂

**Comment by wujunze** [comment]
vimac 兄说的对      我搬砖了
